apiVersion: v1
kind: ServiceAccount
metadata:
  name: postmortems-reports-sa
  namespace: default
  labels:
    app: postmortems-reports
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::444106639146:role/postmortems-reports-access-20250912165628797700000008
